@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiZ3ZlcmFAdXYubXgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9naXZlbm5hbWUiOiJHdWlsbGVybW8gVmVyYSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluaXN0cmFkb3IiLCJpc3MiOiJTZXJ2aWRvckZlaUpXVCIsImF1ZCI6IkNsaWVudEZlaUpXVCIsImlhdCI6MTczMjAzMDM1NCwiZXhwIjoxNzMyMDMxNTU0fQ.61dUOmDsGvvA5-9L2kyctiChSo2gKzEU9yMslVeE6_U

GET http://localhost:3000/api/categorias
Authorization: Bearer {{token}}

###

GET http://localhost:3000/api/categorias/2
Authorization: Bearer {{token}}

###

POST http://localhost:3000/api/categorias/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "nombre": "Categoria de prueba"
}

###
PUT http://localhost:3000/api/categorias/16
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "Categoria de prueba editada"
}

###

GET http://localhost:3000/api/categorias/16
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/api/categorias/15
Authorization: Bearer {{token}}